os:
  - linux

language: php
env:
  - DOCKER_COMPOSE_VERSION=1.17.1
php:
  - '7.1'
services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - /bin/ls -a
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install

script:
  - npm run production
  - docker-compose build

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $DOCKER_ORG/www $DOCKER_ORG/www:latest;
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push $DOCKER_ORG/www:latest;
  fi
- if [ "$TRAVIS_BRANCH" == "develop" ]; then docker tag $DOCKER_ORG/www $DOCKER_ORG/www:devel;
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; docker push $DOCKER_ORG/www:devel;
  fi
