name: CI to Staging
on:
  push:
    branches: [main]
jobs:
  common-build:
    uses: vatusa/gitops/.github/workflows/common-build.yml@main
    with:
      image-name: 'www'
    secrets: inherit
  common-dev-ci:
    uses: vatusa/gitops/.github/workflows/common-dev-ci.yml@main
    needs: common-build
    with:
      image-name: 'www'
      kustomization-folder: 'current'
    secrets: inherit
