# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [master, dev]
env:
  KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Install Dependencies and Compile Assets
        run: |
          npm install
          npm run prod
          
      - name: Build Docker Image
        run: docker-compose build --no-cache
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub (Master)
        if: contains(github.ref, 'master')
        run: |
          docker tag vatusa/www vatusa/www:${{ steps.vars.outputs.sha_short }}
          docker push vatusa/www:${{ steps.vars.outputs.sha_short }}
          
      - name: Push to Docker Hub (Dev)
        if: contains(github.ref, 'dev')
        run: |
          docker tag vatusa/www vatusa/www:dev
          docker push vatusa/www:dev
          
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.2'

      - name: Deploy to Kubernetes Cluster - Update Deployment
        if: contains(github.ref, 'master')
        run: |
          kubectl set image deployment/www *=vatusa/www:${{ steps.vars.outputs.sha_short }} -n web
          
      - name: Deploy to Kubernetes Cluster - Update Cron Job
        if: contains(github.ref, 'master')
        run: |
          kubectl set image cronjob/www-cron *=vatusa/www-cron:${{ steps.vars.outputs.sha_short }} -n web
          
          
      - name: Deploy to Kubernetes Cluster - Update Queue Worker
        if: contains(github.ref, 'master')     
        run: |
          kubectl set image deployment/www-queue *=vatusa/www-queue:${{ steps.vars.outputs.sha_short }} -n web
